name: test-e2e
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, release-*]
    paths:
      - "**.go"
      - '**.py'
      - '**.toml'
      - '**.sh'
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
      - "test/**"
      - "e2e/**"
      - "devops/**"
jobs:
  e2e-mysql:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_DATABASE: lake
          MYSQL_USER: merico
          MYSQL_PASSWORD: merico
          MYSQL_ROOT_PASSWORD: root
    container: mericodev/lake-builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git config --global --add safe.directory $(pwd)
      - name: Build Python
        run: |
          cd backend
          echo "Building Python"
          make build-python
      - name: Cache test-e2e
        id: cache-test-e2e
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test-mysql
        env:
          DB_URL: mysql://root:root@db:3306/lake?charset=utf8mb4&parseTime=True
          E2E_DB_URL: mysql://root:root@db:3306/lake?charset=utf8mb4&parseTime=True
        run: |
          go version
          cp env.example .env
          cd backend
          make e2e-plugins-test
          make e2e-test

  e2e-postgres:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.2
        env:
          POSTGRES_DB: lake
          POSTGRES_USER: merico
          POSTGRES_PASSWORD: merico
    container: mericodev/lake-builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git config --global --add safe.directory $(pwd)
      - name: Build Python
        run: |
          cd backend
          echo "Building Python"
          make build-python
      - name: Cache test-e2e-pg
        id: cache-test-e2e-pg
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ${{ env.GOPATH }}/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test-pg
        env:
          DB_URL: postgres://merico:merico@db:5432/lake
          E2E_DB_URL: postgres://merico:merico@db:5432/lake
        run: |
          go version
          cp env.example .env
          cd backend
          make e2e-plugins-test
          make e2e-test
